### PR TITLE
Add Issue Templates (again)

### PR DESCRIPTION
**Pull request by brndnln**
This will add the following issue templates:
 - Bug reports (including @fruitcake5's suggestion)
 - Feature requests
 - Developer feature requests
 - Wiki edits

### CODE REVIEW

**Review by superjacobl — APPROVED** [review]
Very good

**Review by SpikeViper — APPROVED** [review]
No eggs located

**Review by fruitcake5 — APPROVED** [review]
Very nice!

**Comment by brndnln** [comment]
So, Spike merging #60 caused some issues so I will just redo this with all the changes + some more as the bug report issue template has egg in it.

**Pull request closed without merging**
