### PR TITLE
More Easter eggs for birthdays

### PR DESCRIPTION
**Pull request by Coca16**
This is better then Niami's because it includes fancier stuff

### CODE REVIEW

**Comment by NiamiTV** [comment]
ok fair enough its funnier

**Review by fruitcake5 — APPROVED** [review]
I hope the reverting of the sham was not a sham

**Review by SpikeViper — APPROVED** [review]

**Comment by brndnln** [comment]
Not much of an easter egg anymore is it?

**Comment by kiwiscripter** [comment]
that's what I thought @brndnln

**Pull request merged**
